version: '2'
services:
#  meteor_1:
#    image: wdhif/transcode-meteor
#    ports:
#      - "80:80"
#    links:
#      - mongo_1
#      - mongo_2
#      - mongo_3
#    environment:
#      - MONGO_URL=mongodb://mongo_1,mongo_2,mongo_3/transcode?replicaSet=transcode
#      - ROOT_URL=http://meteor_1
  mongo_1:
    image: mongo
    ports:
      - "27017"
    command: --smallfiles --replSet transcode
  mongo_2:
    image: mongo
    ports:
      - "27018"
    command: --smallfiles --replSet transcode
  mongo_3:
    image: mongo
    ports:
      - "27019"
    command: --smallfiles --replSet transcode
  mongo_setup:
    image: ubuntu
    volumes: 
      - ./scripts:/scripts
    entrypoint: /scripts/mongoSetup.sh
#  core:
#    image: celery
#    environment:
#      - C_FORCE_ROOT=true
#      - BROKER_URL=amqp://guest@broker//
#    links:
#      - broker
#  broker:
#    image: rabbitmq
#  worker:
#    image: celery
#    environment:
#      - C_FORCE_ROOT=true
#      - BROKER_URL=amqp://guest@broker//
#    links:
#      - core
#      - broker
#    command: bash -c "sleep 5 && celery -A transcode worker --concurrency=1"
