version: '2'
services:
  meteor:
    image: wdhif/transcode-meteor
    expose:
      - "80"
    links:
      - mongo_1
      - mongo_2
      - mongo_3
      - mongo_setup
    environment:
      ROOT_URL: "http://balancer"
      CLUSTER_BALANCER_URL: "http://balancer"
      MONGO_URL: "mongodb://mongo_1:27017,mongo_2:27017,mongo_3:27017/transcode?replicaSet=transcode"
      CLUSTER_DISCOVERY_URL: "mongodb://mongo_1:27017,mongo_2:27017,mongo_3:27017/transcode?replicaSet=transcode"
      CLUSTER_SERVICE: "web"
      DATABASE: transcode
      REPLICA_SET_ID: transcode
      PRIMARY_MEMBER: mongo_1:27017
      SECONDARY_MEMBERS: mongo_2:27017,mongo_3:27017
      METEOR_SETTINGS: '{"mail":{"protocol":"smtp","username":"smalttestings@gmail.com","password":"VERtZrAiRliTenumpTIpHoR","server":"smtp.gmail.com","port":"465"},"stripe":{"secretKey":"sk_test_BcmFKWJ43jmwtW5cDwHKZqVf"},"public":{"stripe":{"currency":"usd","publishableKey":"pk_test_GMW5EdI51d75nonOsRvu10Db","websiteName":"Transcode"},"formats":{"video":["3gp","avi","f4v","flv","mkv","mov","mp4","mpeg","mpg","ogv","webm","wmv","yuv"],"audio":["aac","ac3","flac","mp3","oga","wav","wma"]}},"data":"/data","broker":"amqp://guest:guest@broker//","google":{"clientId":"398622006737-pj4be88r404b2tu89lcag9evqcg4v416.apps.googleusercontent.com","secret":"pOGZyxoEJkZ2FKK8KO9xgxzk"},"facebook":{"clientId":"1726755800903746","secret":"cefb82cefed87ac53af8f6738906a5a4"}}'
    volumes:
      - ./.data:/data
  balancer:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - meteor
    environment:
      STATS_AUTH: "root:root"
      STATS_PORT: "3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo_1:
    image: mongo
    command: --smallfiles --replSet transcode --quiet
  mongo_2:
    image: mongo
    command: --smallfiles --replSet transcode --quiet
  mongo_3:
    image: mongo
    command: --smallfiles --replSet transcode --quiet
  mongo_setup:
    image: wdhif/mongo-replicaset-setup
    links:
      - mongo_1
      - mongo_2
      - mongo_3
    environment:
      DATABASE: transcode
      REPLICA_SET_ID: transcode
      PRIMARY_MEMBER: mongo_1:27017
      SECONDARY_MEMBERS: mongo_2:27017,mongo_3:27017
  broker:
    image: wdhif/transcode-rabbitmq
    expose:
      - "5672"
      - "15672"
  core:
    image: wdhif/transcode-celery
    expose:
      - "5555"
    links:
      - broker
    environment:
      - C_FORCE_ROOT=true
      - BROKER_URL=amqp://guest:guest@broker//
      - CELERY_BROKER_URL=amqp://guest:guest@broker//
    volumes:
      - ./scripts:/home/user
      - ./.data:/data
    command: bash -c "celery -A transcode worker -l info --app=core.core.app -Q core"
  worker:
    image: wdhif/transcode-celery
    expose:
      - "5555"
    links:
      - core
      - broker
    environment:
      - C_FORCE_ROOT=true
      - BROKER_URL=amqp://guest:guest@broker//
      - CELERY_BROKER_URL=amqp://guest:guest@broker//
      # - CELERY_APP=tasks
    volumes:
      - ./scripts:/home/user
      - ./.data:/data
    command: bash -c "celery -A transcode worker -l info --app=worker.worker.app"
