version: '2'
services:
  meteor_1:
    image: wdhif/transcode-meteor
    ports:
      - "80:80"
    links:
      - mongo_1
      - mongo_2
      - mongo_3
      - mongo_setup
    environment:
      - MONGO_URL=mongodb://mongo_1,mongo_2,mongo_3/transcode?replicaSet=transcode
      - ROOT_URL=http://meteor_1
  mongo_1:
    image: mongo
    command: --smallfiles --replSet transcode --quiet
  mongo_2:
    image: mongo
    command: --smallfiles --replSet transcode --quiet
  mongo_3:
    image: mongo
    command: --smallfiles --replSet transcode --quiet
  mongo_setup:
    image: wdhif/mongo-replicaset-setup
    links:
      - mongo_1
      - mongo_2
      - mongo_3
    environment:
      DATABASE: transcode
      REPLICA_SET_ID: transcode
      PRIMARY_MEMBER: mongo_1:27017
      SECONDARY_MEMBERS: mongo_2:27017,mongo_3:27017
  data:
    image: ubuntu
    command: sleep infinity
    volumes:
      - /var/lib/data
  # core:
  #   image: celery
  #   environment:
  #     - C_FORCE_ROOT=true
  #     - BROKER_URL=amqp://guest@rabbitmq//
  #   links:
  #     - broker
  #   volumes_from:
  #     - data
  # broker:
  #   image: rabbitmq
  # worker:
  #   image: celery
  #   environment:
  #     - C_FORCE_ROOT=true
  #     - BROKER_URL=amqp://guest@broker//
  #   links:
  #     - core
  #     - broker
  #   volumes_from:
  #     - data
  #   command: bash -c "sleep 5 && celery -A transcode worker --concurrency=1"
