version: '2'
services:
  meteor:
    image: wdhif/transcode-meteor
    expose:
      - "80"
    links:
      - mongo_1
      - mongo_2
      - mongo_3
      - mongo_setup
    environment:
      ROOT_URL: "http://balancer"
      CLUSTER_BALANCER_URL: "http://balancer"
      MONGO_URL: "mongodb://mongo_1:27017,mongo_2:27017,mongo_3:27017/transcode?replicaSet=transcode"
      CLUSTER_DISCOVERY_URL: "mongodb://mongo_1:27017,mongo_2:27017,mongo_3:27017/transcode?replicaSet=transcode"
      CLUSTER_SERVICE: "web"
      DATABASE: transcode
      REPLICA_SET_ID: transcode
      PRIMARY_MEMBER: mongo_1:27017
      SECONDARY_MEMBERS: mongo_2:27017,mongo_3:27017
      METEOR_SETTINGS: '{"mail":{"protocol":"smtp","username":"smalttestings@gmail.com","password":"VERtZrAiRliTenumpTIpHoR","server":"smtp.gmail.com","port":"465"},"stripe":{"secretKey":"sk_test_BcmFKWJ43jmwtW5cDwHKZqVf"},"public":{"stripe":{"currency":"USD","publishableKey":"pk_test_GMW5EdI51d75nonOsRvu10Db","websiteName":"Transcode"}}}'
    volumes:
      - ./.data:/data
  balancer:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - meteor
    environment:
      STATS_AUTH: "root:root"
      STATS_PORT: "3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo_1:
    image: mongo
    command: --smallfiles --replSet transcode --quiet
  mongo_2:
    image: mongo
    command: --smallfiles --replSet transcode --quiet
  mongo_3:
    image: mongo
    command: --smallfiles --replSet transcode --quiet
  mongo_setup:
    image: wdhif/mongo-replicaset-setup
    links:
      - mongo_1
      - mongo_2
      - mongo_3
    environment:
      DATABASE: transcode
      REPLICA_SET_ID: transcode
      PRIMARY_MEMBER: mongo_1:27017
      SECONDARY_MEMBERS: mongo_2:27017,mongo_3:27017
  core:
    image: wdhif/transcode-celery
    expose:
      - "5555"
    links:
      - broker
    environment:
      - C_FORCE_ROOT=true
      - BROKER_URL=amqp://guest:guest@broker//
      - CELERY_BROKER_URL=amqp://guest:guest@broker//
    volumes:
      - ./scripts:/home/user
      - ./.data:/data
    command: bash -c "celery -A core worker -l info --app=core.core.app"
  broker:
    image: rabbitmq
    expose:
      - "5672"
  worker:
    image: wdhif/transcode-celery
    expose:
      - "5555"
    links:
      - core
      - broker  
    environment:
      - C_FORCE_ROOT=true
      - BROKER_URL=amqp://guest:guest@broker//
      - CELERY_BROKER_URL=amqp://guest:guest@broker//
      # - CELERY_APP=tasks
    volumes:
      - ./scripts:/home/user
      - ./.data:/data
    command: bash -c "celery -A worker worker -l info --app=worker.worker.app"
